---

name: "Upload robots.txt file to release"
run-name: "Upload robots.txt file to release"

on:
  release:
    types:
      - published

jobs:
  upload-robots-txt-file-to-release:
    name: "Upload robots.txt file to release"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Upload"
        run: gh --repo "${REPO}" release upload "${TAG}" robots.txt
        env:
          REPO: ${{ github.repository }}
          TAG: ${{ github.event.release.tag_name }}
